#!/bin/bash

# MX info:
echo ""
dig=`dig mx $1 +short | cut -c 3-`
echo "MX maskiner fra: $1:"
for address in $dig;
do
  addressIPv4=`nslookup $address | grep 'Address:' | tail -n 2 | head -n 1 | cut -d ' ' -f 2`
  addressIPv6=`nslookup $address | grep 'Address:' | tail -n 1 | cut -d ' ' -f 2`
  echo "- Domene: ${address%?}, IPv4: $addressIPv4, IPv6: $addressIPv6"
done
echo ""

# TXT info
echo "TXT info:"

find_ip_from_domain() {
    
    nslookup -type=txt $1 | grep v=spf1 | tr ' ' '\n' | grep ip
    SPF_include=`nslookup -type=txt $1 | grep v=spf1 | tr ' ' '\n' | grep include | cut -d ':' -f 2`
    
    for domain in $SPF_include; do
        find_ip_from_domain $domain
    done



    SPF_redirect=`nslookup -type=txt $1 | grep v=spf1 | tr ' ' '\n' | grep redirect | cut -d '=' -f 3`
    for domain in $SPF_redirect; do
        find_ip_from_domain $domain
    done
}

find_ip_from_domain $1

